### ISSUE TITLE
Does it gets Updates daily ?

### ISSUE THREAD

**Issue by zoroya1** [Lijukay/Qwotable#24]
Thank you for the app and all the quotes :)
Just wanted to ask that do you update new features in same version of the release ?
For example, i have version 1 installed from obtainium and still it asks me to update the app, i think it will be proper if new features are introduced in subsequent releases i.e 1.1, 1.2 and so on....

Steps to produce the loop :
- Install the qwotable using obtainium
- It shows update, even after updating it shows another update

Maybe there is some error in release numbering ?

**Comment by Lijukay** [comment]
Hey, I will have a look at this. Just to make sure, I have never heard of obtainium. What exactly is this?

Also normally, version 1 is the latest version. It uses versionCode 10, which, as far as I know, exists only once in all releases

**Comment by Lijukay** [comment]
My fault. I know about Obtainium. I will have a look ^^

**Comment by Lijukay** [comment]
Mhh, so there is something strange for sure. It detects 1 as version and the latest release tag v10 as two different things meanwhile tag v10 == 1.

I am not sure why this is but I will have a look at the code of Obtainium in order to make my updates more precise.

**Comment by Lijukay** [comment]
For now, what you can do is:

In Obtainium, click on my app. Then click on the pen and set `Version Detection` to `Use Date as Version`. It will stop showing the endless update loop.

**Comment by Lijukay** [comment]
Okay so Flutter is a bit complicated to read. Yet it seems like Obtainium is taking two different parts to detect the version:

The newer version:
Obtainium takes the tag (in this case v10)

Installed Version:
Obtainium takes the VersionName (in this case 1)

Since v10 is not equal to 1, it says that there is an update tho there is not.

To fix this, I might change VersionName to the tag's name. I will check if this causes trouble. If not, this might eventually fix the issue with Obtainium ^^

**Comment by zoroya1** [comment]
I will ignore that update icon for time being, but generally what i habe seen is apk tags x.y or x.y.z used frequently

Maybe Bnyro and Izzyondroid can help you, they are best and helpful people i noticed around github :)
Just append `@`infront of above names and by chance they will notice and offer some help 😃

**Comment by Lijukay** [comment]
You are right.
Well @Bnyro or @Izzyondroid, do you have any idea on how I can make my versioning a bit more efficient?

**Comment by Bnyro** [comment]
Yes, in general the version name (inside `build.gradle` and the release tag should be similar.
In the end, the version code mostly exists to prevent user from downgrading the app, what's really relevant (and should be used when it comes to user facings) is the version name. 
You can take a look at how we're handling releases at LibreTube (https://github.com/libre-tube/LibreTube/releases/tag/v0.13.1), basically the tag is `v{versionName}` and the version code is not visible anywhere since it's really not commonly used for labeling releases.
I'd assume Obtainium just compares the numbers inside the release tag and the version name of your installation, but I didn't look at its source code yet so that might not be accurate.
However, as far as I can tell there are no issues when just doing everything as described above.
However that's only based on my experiences, Izzy probably has more of that :)

**Comment by Lijukay** [comment]
Thank you for the quick response.
Well if it does not lead to any problems I might consider to make versionName similar to the tag.
The tag is v{versionCode} which is because of the FDroid tag update check.
If Izzy is telling the same, I might consider in changing versionName.

**Comment by IzzySoft** [comment]
Well, kinda. Actually, F-Droid.org usually does not go by the tag name (CheckUpdates looks at the matching files (`build.gradle` first, then Manifest – unless something specific was defined) at the latest tag, watching out if a `versionCode`(!) was found that's newer than the one present in the repo. The updater for my repo (which doesn't build from source) goes by tag names – but then it can be either `versionName` or `versionCode` (actually the latter is much easier to compare as it's just an integer). So renaming tags won't speed up updates.

> Since my app is available on FDroid, providing new features without increment the version number will only lead to mistakes.

Without increasing `versionCode`, that wouldn't even be fetched – as outlined, CheckUpdates only accepts `versionCode`s *higher*  than those already present at F-Droid.

I have no idea however which way Obtainium makes sure a signaled update is really a newer version (I don't even use it). As there's no real rule how tag names are constructed, they must have set up some algorithm to deal with different implementations (I do have that with my repo). So if they fetch or suggest the wrong one, it's something **they** should fix. As long as the tag name is clearly identifying a `versionCode` **or** `versionName` by **containing** it with a fixed pattern (e.g. `v<versionName>`, `c<versionCode>`, `android-`versionName`) so it can be matched against, it's the task of the "fetcher" to match it, IMHO.

That said, I see no harm in using the one or the other. Just if you intend to switch, make sure that e.g. F-Droid does not somehow depend on the current one (it's possible to define patterns to stick to, to e.g. not fetch pre-releases not intended for the public).

And there you go:

```yaml
Binaries: https://github.com/Lijukay/Qwotable/releases/download/v%c/Qwotable.V.%c.apk
```

so changing the pattern would break updates for F-Droid. That line could be changed for future updates, but then might render existing ones invalid (as the new pattern wouldn't match existing builds, and thus on a cross-check would mark them "not reproducible"). So I'd rather have Obtainium fix it on their end.

**Comment by Lijukay** [comment]
Well seems like I can't fix this then.
